# Generated by Django 5.0.2 on 2024-03-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblocks',
            name='uniqueId',
        ),
        migrations.RemoveField(
            model_name='homeslides',
            name='uniqueId',
        ),
        migrations.RemoveField(
            model_name='products',
            name='uniqueId',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='homeblocks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeslides',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
