# Generated by Django 5.0.2 on 2024-03-14 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.products'),
            preserve_default=False,
        ),
    ]
