# Generated by Django 5.0.2 on 2024-03-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_products_size_size_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
        migrations.AlterField(
            model_name='products',
            name='offerPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
