# Generated by Django 5.0.2 on 2024-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_products_collection_alter_products_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
