# Generated by Django 5.0.2 on 2024-03-18 13:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='anonymous_id',
            field=models.CharField(default=core.models.generate_random_id, max_length=255, unique=True),
        ),
    ]
