# Generated by Django 5.0.2 on 2024-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_wishlist_anonymous_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
