# Generated by Django 5.0.2 on 2024-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_order_country_order_email_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
