# Generated by Django 5.0.2 on 2024-03-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products'),
        ),
    ]
