# Generated by Django 5.0.2 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_orderitems_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
