# Generated by Django 5.0.2 on 2024-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
